-- Database Manager 4.2.5 dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `tasks`;
CREATE TABLE `tasks` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `task_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `task_points` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `task_desc` text COLLATE utf8_unicode_ci NOT NULL,
  `task_expiry` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `is_imp` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `task_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `task_user_id` text COLLATE utf8_unicode_ci,
  `status` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `tasks` (`id`, `task_name`, `task_points`, `task_desc`, `task_expiry`, `is_imp`, `task_type`, `task_user_id`, `status`, `created_at`, `updated_at`) VALUES
(4,	'Tinder U After-party',	'25',	'<p>You guys get a chance to plan your city\'s Tinder U Meet as well as an after party! Following are the guidelines for this task:<br /><br />1) We&rsquo;ll be forming teams of 4-5 people within your city. You can find the list of teams <a href=\"https://drive.google.com/file/d/10lcL2KQwARiyRCJkwukEISckcqjV41Xw/view?usp=sharing\" target=\"_blank\" rel=\"noopener\">here.</a> <br />2) There is a team captain assigned to every team. The team captains have to make WhatsApp groups with their respective team members and add their city head to it. <br />3) Each team has to plan a meet and an after-party. Be creative with your ideas. For example, you could organize a theme based party or include games in your plan. Just make it fun and engaging so that everybody can interact with each other. <br />4) Plan your meet for any date between 3rd October to 23rd October. <br />5) Every Team has to submit their plan by <strong>11:59pm, 2nd October, 2018 i.e. Tuesday</strong>. You have to make a word document /pdf/ ppt including the following things:<br /><br /><br /><br />&lt;Theme/ Activities&gt;<br />You can upload your files <a href=\"https://goo.gl/forms/XFEuzDP8f6XrR0Xq2\">here.</a>&nbsp;<br />6) From each city, we\'ll pick one winner. The winning party idea will be sponsored by us for all the reps in your city and the <strong>winning team instantly goes to the next level.</strong></p>',	'2018-10-04',	NULL,	NULL,	NULL,	'1',	'2018-09-26 20:25:43',	'2018-10-02 10:15:36'),
(5,	'Campus Spots',	'15',	'<p>Hey there,</p>\r\n<p>So we were thinking that lets put our heads together pull a small cheeky stunt on your campus.</p>\r\n<p>Here\'s what we were thinking :</p>\r\n<p>1) Tell us what is the most popular hangout spot on your campus. It\'s every student\'s go-to spot to chill with their friends and half of your college stories have taken place here. For example, for Hansraj College, LP (Lover\'s Point :P )is that spot.</p>\r\n<p>2) Tell us why it\'s popular. For example, does it have a graffiti where everybody takes pictures? Or Is it the street shop right outside of college that serves just the right flavor of chai?</p>\r\n<p>3) Write a copy/tagline about the place linking it with Tinder. Something that only students from your college would relate to. For example, it\'s difficult to find students in Hansraj except for LP and it\'s famous for the coffee you get there.</p>\r\n<p>So <a href=\"https://drive.google.com/drive/folders/1YQCMJuJYg-E0VCyd4alc2Q0do3BgGKPv\" target=\"_blank\" rel=\"noopener\">these</a> are what we came up with.&nbsp;<br /><br />4) Share all of the above with us <a href=\"https://docs.google.com/forms/d/e/1FAIpQLScYFri1CobST8aB7FhXr3T3eOENw9uApVSzBEu04GxoACYDpA/viewform?usp=sf_link\" target=\"_blank\" rel=\"noopener\">here</a>.&nbsp;</p>',	'2018-10-04',	NULL,	NULL,	NULL,	'1',	'2018-09-30 17:47:36',	'2018-10-02 10:15:06'),
(6,	'Tinder Advisor',	'25',	'<p>Become a Tinder Advisor and teach your friends how to Tinder with #TinderTips. <br />Tinder Advisor is an umbrella task/summary task which contains two different tasks- Part I and Part II<br />The guidelines for TINDER ADVISOR- Part I are as follows: <br />1) We&rsquo;re sharing 5 templates with you to put up as your Instagram Stories. You can find the templates <a href=\"https://drive.google.com/drive/u/1/folders/1BNwb-uWk5UFwNp2JFJg4NdG8eGpfe6I_\">here</a>.&nbsp;<br />2) Put them up as your Instagram Stories. First, upload the cover template followed by Tinder Tips templates. Be sure to tag @tinder_india and add #TinderU. Go crazy with the GIFS when you put up your story.&nbsp;<br />As an example, <a href=\"https://drive.google.com/file/d/1aQ9X4pcYsbWbXrDfIZB5bmIpmCzZSMMz/view?usp=sharing\">this</a> is what we could come up with. Can you do better?&nbsp;<br />The guidelines for part II are as follows: <br />1) Wear your Tinder Advisor t-shirt on your campus <br />2) Give your friends Tinder Lessons in person. Answer their questions regarding Tinder and help them make their profile better!</p>',	'2018-10-05',	NULL,	'user_task',	'15368',	'1',	'2018-10-01 09:35:07',	'2018-10-01 09:56:09'),
(7,	'Tinder Advisor',	'25',	'<p>Become a Tinder Advisor and teach your friends how to Tinder with #TinderTips. <br />Tinder Advisor is an umbrella task/summary task which contains two different tasks- Part I and Part II<br />The guidelines for TINDER ADVISOR- Part I are as follows: <br />1) We&rsquo;re sharing 5 templates with you to put up as your Instagram Stories. You can find the templates <a href=\"https://drive.google.com/drive/u/1/folders/1BNwb-uWk5UFwNp2JFJg4NdG8eGpfe6I_\">here</a>.&nbsp;<br />2) Put them up as your Instagram Stories. First, upload the cover template followed by Tinder Tips templates. Be sure to tag @tinder_india and add #TinderU. Go crazy with the GIFS when you put up your story.&nbsp;<br />As an example, <a href=\"https://drive.google.com/file/d/1aQ9X4pcYsbWbXrDfIZB5bmIpmCzZSMMz/view?usp=sharing\">this</a> is what we could come up with. Can you do better?&nbsp;<br />The guidelines for part II are as follows: <br />1) Wear your Tinder Advisor t-shirt on your campus <br />2) Give your friends Tinder Lessons in person. Answer their questions regarding Tinder and help them make their profile better!</p>',	'2018-10-02',	NULL,	'user_task',	'3940',	'1',	'2018-10-01 11:54:25',	'2018-10-01 12:03:12'),
(8,	'Tinder On Campus',	'25',	'<p><br />We want you to take Tinder to the iconic places in your campus. ;)<br />Following are the guidelines for this task:<br />1) Take a picture of your hand while holding the phone in front of a popular place in your campus, taking inspiration from the famous Follow Me series. To help you out, we&rsquo;re sharing an example with you. <br />2)Make sure the image shared <a href=\"https://drive.google.com/file/d/1ZsMp4EGisWHqo9ssxIODZnljYcAMwO9u/view?usp=sharing\">here</a> is open on the screen. <br />3)Be as creative as possible and post it on your social media handles with #CollegeOnTinder and #FollowMeTo Tinder in the caption. For example, if you&rsquo;re from Hindu College, your hashtag should be #HinduOnTinder. Make sure your post is public. <br />4) You can find a reference post <a href=\"https://drive.google.com/file/d/1JTBSGriGaD_GwGkeKfBBs323OY5_nuTS/view?usp=sharing\">here</a>.&nbsp;<br />5) Take a screenshot of your post and send it to your city coordinator.</p>',	'2018-10-02',	NULL,	'user_task',	'3940',	'1',	'2018-10-01 11:59:17',	'2018-10-01 12:02:55'),
(9,	'Epic Tinder Profiles',	'40',	'<p>Give the people in your campus an epic Tinder Profile! <br />Following are the guidelines for this task: <br />1) Take a picture of anyone in your campus. It could be your friends, professors or even the dog in your campus that everybody loves. <br />2) Put it up as your Instagram story and caption it with a fun and witty Tinder bio. Use your creativity to make it look like a Tinder Profile! <br />3) Tag @tinder_india and use #CollegeOnTinder for example, if you&rsquo;re from Hindu College, use #HinduOnTinder. <br />5) For your reference,<a href=\"https://drive.google.com/file/d/1P6V-3DitX73OFaM93V-59jrQECyuHf5_/view?usp=sharing\"> this</a> is what we came up with. <br />4) Deadline for this task is 7th October i.e. Sunday. Make sure you post at least one picture per day till the deadline! Send us screenshots of your stories <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSdcLQQi6Dh4hOtakOn8iX4Udun0HPjLSpffowD8wnUidVk6gA/viewform?usp=sf_link\">here.</a></p>',	'2018-10-11',	NULL,	NULL,	NULL,	'1',	'2018-10-03 22:01:55',	'2018-10-10 18:16:11'),
(10,	'Campus Connect',	'10',	'<p>With the Tinder U Campus Rep program, we&rsquo;re building our presence in colleges across India.</p>\r\n<p>While you guys have done a great job of promoting Tinder in your colleges, the task at hand is humongous and we would need more hands/brains to contribute together.&nbsp;</p>\r\n<p>Keeping the above in mind, we aim to build further the presence of Tinder in campus through a specific Campus Influencer Program. As a campus rep, you would be the face and go to person in your campus. To enhance your efforts, we would be getting on board certain influential people to promote specific campaigns only.</p>\r\n<p>You define who these people should be and you ensure maximum leverage from them to create a buzz in the campus.</p>\r\n<p><strong>What\'s required of you?</strong><br /><br />1) Tell us about the right people by you filling <a href=\"https://docs.google.com/forms/d/e/1FAIpQLScvVmfaWfejGjJZL7CpBCIybrRPczV0Hp6PHEEHQMi0vWH2qA/viewform?usp=sf_link\" target=\"_blank\" rel=\"noopener\">this form</a>. They can be the dram soc president or great sportsmen or just have exceptional social skills. They do have to have some distinguishing qualities from the rest of the crowd and ideally have a significant social media presence. You can give us up to 10 names for your college.</p>\r\n<p>2) You can tell them that this is regarding an opportunity with Tinder U and that we\'re looking to collaborate.<br /><br />3) The deadline for this task is 11th October i.e. Thursday.</p>',	'2018-10-15',	NULL,	NULL,	NULL,	'1',	'2018-10-09 12:15:28',	'2018-10-09 12:15:28');

-- 2018-10-11 07:12:04
